name: "FRP Client"
description: "You can use this tool to achieve remote access to local Home Assistant OS by port forwarding"
version: "1.0.2"
slug: "frp_client"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  serverAddr: "example.com"
  serverPort: 7000
  authUser: "admin"
  authToken: "123456789"
  remotePort: 8123
  # Deprecated 
  # ------------
  # webServerPort: 7500
  # webServerUser: "admin"
  # webServerPassword: "123456789"
  # customDomain: "example.com"
  # proxyName: "homeassistant"
  proxyType: "http"
  # ------------
schema:
  serverAddr: str
  serverPort: int
  authToken: str
  authUser: str
  remotePort: int
  # Deprecated 
  # ------------
  # webServerPort: int
  # webServerUser: str
  # webServerPassword: str
  # customDomain: str
  # proxyName: str
  # ------------
  proxyType: list(tcp|http|https)
 
