serverAddr = "your_server_addr"
serverPort = 7000
auth.method = "token"
user = "admin"
auth.token = "123456789"

log.to = "/share/frpc.log"
# trace, debug, info, warn, error
log.level = "trace"
log.maxDays = 3

# transport.tls.enable = false
# transport.tls.certFile = "/share/frp/fullchain.pem"
# transport.tls.keyFile = "/share/frp/privkey.pem"
# transport.tls.trustedCaFile = "/share/frp/fullchain.pem"
# transport.tls.serverName = "your_server_name"

# webServer.addr = "0.0.0.0"
# webServer.port = 7500
# webServer.user = "admin"
# webServer.password = "123456789"

[[proxies]]
name = "your_proxy_name"
type = "your_proxy_type"
transport.useEncryption = false
transport.useCompression = false
localPort = 8123
localIP = "0.0.0.0"
remotePort = 8123


